/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as ProcessingTimesCountryRouteImport } from './routes/processing-times.$country'
import { Route as EmbassyCityRouteImport } from './routes/embassy.$city'
import { Route as VisaCountryTypeRouteImport } from './routes/visa.$country.$type'
import { Route as CompareCountryACountryBRouteImport } from './routes/compare.$countryA.$countryB'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingTimesCountryRoute = ProcessingTimesCountryRouteImport.update({
  id: '/processing-times/$country',
  path: '/processing-times/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbassyCityRoute = EmbassyCityRouteImport.update({
  id: '/embassy/$city',
  path: '/embassy/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaCountryTypeRoute = VisaCountryTypeRouteImport.update({
  id: '/visa/$country/$type',
  path: '/visa/$country/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareCountryACountryBRoute = CompareCountryACountryBRouteImport.update({
  id: '/compare/$countryA/$countryB',
  path: '/compare/$countryA/$countryB',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracker': typeof TrackerRoute
  '/terms': typeof TermsRoute
  '/embassy/$city': typeof EmbassyCityRoute
  '/processing-times/$country': typeof ProcessingTimesCountryRoute
  '/compare/$countryA/$countryB': typeof CompareCountryACountryBRoute
  '/visa/$country/$type': typeof VisaCountryTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracker': typeof TrackerRoute
  '/terms': typeof TermsRoute
  '/embassy/$city': typeof EmbassyCityRoute
  '/processing-times/$country': typeof ProcessingTimesCountryRoute
  '/compare/$countryA/$countryB': typeof CompareCountryACountryBRoute
  '/visa/$country/$type': typeof VisaCountryTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracker': typeof TrackerRoute
  '/terms': typeof TermsRoute
  '/embassy/$city': typeof EmbassyCityRoute
  '/processing-times/$country': typeof ProcessingTimesCountryRoute
  '/compare/$countryA/$countryB': typeof CompareCountryACountryBRoute
  '/visa/$country/$type': typeof VisaCountryTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/tracker'
    | '/terms'
    | '/embassy/$city'
    | '/processing-times/$country'
    | '/compare/$countryA/$countryB'
    | '/visa/$country/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/tracker'
    | '/terms'
    | '/embassy/$city'
    | '/processing-times/$country'
    | '/compare/$countryA/$countryB'
    | '/visa/$country/$type'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/tracker'
    | '/terms'
    | '/embassy/$city'
    | '/processing-times/$country'
    | '/compare/$countryA/$countryB'
    | '/visa/$country/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackerRoute: typeof TrackerRoute
  TermsRoute: typeof TermsRoute
  EmbassyCityRoute: typeof EmbassyCityRoute
  ProcessingTimesCountryRoute: typeof ProcessingTimesCountryRoute
  CompareCountryACountryBRoute: typeof CompareCountryACountryBRoute
  VisaCountryTypeRoute: typeof VisaCountryTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing-times/$country': {
      id: '/processing-times/$country'
      path: '/processing-times/$country'
      fullPath: '/processing-times/$country'
      preLoaderRoute: typeof ProcessingTimesCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embassy/$city': {
      id: '/embassy/$city'
      path: '/embassy/$city'
      fullPath: '/embassy/$city'
      preLoaderRoute: typeof EmbassyCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa/$country/$type': {
      id: '/visa/$country/$type'
      path: '/visa/$country/$type'
      fullPath: '/visa/$country/$type'
      preLoaderRoute: typeof VisaCountryTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$countryA/$countryB': {
      id: '/compare/$countryA/$countryB'
      path: '/compare/$countryA/$countryB'
      fullPath: '/compare/$countryA/$countryB'
      preLoaderRoute: typeof CompareCountryACountryBRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackerRoute: TrackerRoute,
  TermsRoute: TermsRoute,
  EmbassyCityRoute: EmbassyCityRoute,
  ProcessingTimesCountryRoute: ProcessingTimesCountryRoute,
  CompareCountryACountryBRoute: CompareCountryACountryBRoute,
  VisaCountryTypeRoute: VisaCountryTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
